flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Текст', validators=[DataRequired()])
    submit = SubmitField('Сохранить')

flask_blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()). \
        paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html',
                           title='Новый пост', form=form, legend='Новый пост')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление поста',
                           form=form, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (RegistrationForm, LoginForm,
                                    UpdateAccountForm, RequestResetForm,
                                    ResetPasswordForm)
from flask_blog.users.utils import send_reset_email

from flask_blog.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана!'
              'Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page \
                else redirect(url_for('posts.allpost'))

        else:
            flash('Войти не удалось. Пожалуйста, '
                  'проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user) \
            .order_by(Post.date_posted.desc()) \
            .paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' +
                                            current_user.image_file)
    return render_template('account.html', title='Аккаунт',
                           image_file=image_file, form=form, posts=posts,
                           user=user)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с '
              'инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt. \
            generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! '
              'Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Сброс пароля', form=form)

flask_blog/templates/account.html
{% extends "layout.html" %}

{% block head %}
  <style>
    .container{
      margin-bottom: 0.8rem;
    }

    .content-section{
      box-shadow: 10px 20px 8px darkslategray;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }

    a{
      color: #003049;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }
    
    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
  </style>
{% endblock head %}


{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Аккаунт пользователя</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}

                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>   



{% endblock content %}

flask_blog/templates/allpost.html
{% extends "layout.html" %}

{% block head %}
  <style>
    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }

    .card-title{
      margin-bottom: 0 !important;
      font-family: 'Bebas Neue', cursive;
    }

    a{
      color: #003049 !important;
      text-decoration: none;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }

    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */

  </style>
{% endblock head %}

{% block content %}
  {% for post in posts.items %}
  <div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column;"> 
      <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 0 auto;">{{ post.author.username }}</a>
    </article>
    
    <div class="card" style="margin-bottom: 20px;">
      <div class="card-body">
        <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <br>
        <br>
        <p class="card-text">{{ post.content }}</p>
      </div>
      <!-- <div class="card-footer" style="font-size: 20px;">
        <i class="fa fa-heart-o"></i>
        <i class="fa fa-bookmark-o"></i>
      </div> -->
    </div>
  </div>
  {% endfor %}

  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

flask_blog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/home.html
{% extends "layout.html" %}

{% block style %}
    <style>   
        body{
        z-index: 5;
        }

        body:before {
        content: ' ';
        display: block;
        position: fixed;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        object-fit: contain;
        z-index: 1;
        opacity: 0.5;
        background-image: url('../static/images/bg.jpg');
        /* background-repeat: no-repeat; */
        /* background-position: 50% 0; */
        background-size: cover;
        }

        .navbar{ 
            background-color: #e2cfc4;
            box-shadow: 0px 1px 10px black;
        }

        .container{
            position: relative;
            z-index: 5;
        }
        
        .heading > h1{
            font-size: 55px;
            font-family: 'Alice', serif;
            color: black;
            text-shadow: 2px 2px #a44a3f;
        }

        .card-text{
            text-align: justify;
            color: rgb(43, 37, 37);
            font-weight: 500;
            font-size: 22px;
        }

        .container > button{
            color: blue;
            padding: 7px;
            border:1px solid blue;
            border-radius: 5px;
            transition: 0.3s ease; 
        }

        .container > button:hover{
            color: white;
            background-color: blue;
            /* padding: 5px; */
        }
    </style>
{% endblock style %}

{% block content %}
<div class="container" style="margin: 12rem 4rem; text-align: center;">
    <div class="heading">
        <h1>ДОБРО ПОЖАЛОВАТЬ!📝</h1>
    </div>
    <hr class="w3-border-grey" style="margin:auto; width:40%;">
    <br>
    <div class="content-body">
        <p class="card-text" id="para">Добро пожаловать в мой <strong><em> блог!</em></strong>
            Большое спасибо за посещение. Я рад видеть вас на просторах моего блога! Это так здорово видеть
            вас здесь. Позвольте мне сказать вам одну вещь: вы можете не только просматривать
            новые посты, но и получать обновления...😄</p>
    </div>
    <br>

    
    <!-- <div class="card" style="border-bottom-left-radius: 50px; border-top-right-radius: 50px; background-color:  #2ec4b6; box-shadow: 10px 15px 10px lightslategray;">
        <div class="card-body" style="color: white;">
            <br>
        </div>
    </div> -->
</div>
{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Alice&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

    {% if title %}
        <title>Flask-блог - {{ title }}</title>
    {% else %}
        <title>Flask-блог</title>
    {% endif %}

    {% block head %} {% endblock head %}

    <style>
      body{
        background-color: #e5e5e5;
        margin-top: 6.5rem;
      }

      .navigation-links{
        color: white !important;
        font-weight: 500;
        background-color: rgb(183, 214, 252);
        border-radius: 5px;
        border-bottom: 4px solid blue;
        margin: 5px;
        background-size: 200% 200%;
        background-image: linear-gradient( transparent 50%, rgb(79, 128, 233) 50%);
        transition: background-position 300ms, color 300ms ease, border-color 300ms ease;      
      }

      .navigation-links:hover{
        color: white;
        background-image: linear-gradient( transparent 50%, #3a86ff 50%);
        background-position: 0% 100%;
      }

      .navbar{
        background-color: #c6def1; 
        box-shadow: 0px 1px 10px black;
      }

      .navbar .container{
        margin-bottom: 0;
      }
    </style>

    
  {% block style %} {% endblock style %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/" style="color: rgb(7, 85, 173); font-family: 'Lobster', cursive; font-weight: 800; font-size: 30px;">Мой блог</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if current_user.is_authenticated %}
            <h4>Привет, {{ current_user.username }}!</h4>
          {% endif %}
          <div class="collapse navbar-collapse" id="navbarToggle" style="justify-content: flex-end;">
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link navigation-links" href="{{url_for('users.account') }}"><i class="fa fa-user"></i>Профиль</a>
                    <a class="nav-item nav-link navigation-links" href="{{ url_for('posts.new_post') }}"><i class="fa fa-plus"></i>Новый пост</a>


                    <a class="nav-item nav-link navigation-links" href="{{ url_for('users.logout') }}"><i class="fa fa-sign-out"></i>Выйти</a>
                    <a class="nav-item nav-link navigation-links" href="{{ url_for('posts.allpost') }}"><i class="fa fa-th"></i>Посты</a>


                {% else %}
                    <a class="nav-link nav-item navigation-links" href="{{url_for('users.login') }}">Войти</a>
                    <a class="nav-link nav-item navigation-links" href="{{url_for('users.register') }}">Зарегистрироваться</a>
                {% endif %}
            </div>

          </div>
        </div>
      </nav>
    </header>
    
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-10">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Авторизация</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>
                </small>




            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Нужен аккаунт? <a class="ml-2" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
            </small>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/post.html
{% extends "layout.html" %}

{% block head %}
  <style>
    .container{
      margin-bottom: 0.8rem;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }
    
    .card-title{
      margin-bottom: 0 !important;
      font-family: 'Bebas Neue', cursive;
    }

    a{
      color: #003049 !important;
      text-decoration: none;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }
    
    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
  </style>
{% endblock head %}

{% block content %}
<div class="container" style="display: flex;">
  <article class="media" style="display: flex; flex-direction: column;"> 
    <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
  </article>
  
  <div class="card" style="margin-bottom: 20px;">
    <div class="card-body">
      <h4 class="card-title">{{ post.title }}</h4>
      <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
      <br>
      <br>
      <p class="card-text">{{ post.content }}</p>
    </div>
    <div class="card-footer" style="font-size: 20px;">
      <!-- <i class="fa fa-heart-o"></i>
      <i class="fa fa-bookmark-o"></i> -->
      {% if post.author == current_user %}
        <div class="card-footer" style="font-size: 20px;"> {% if post.author == current_user %}<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id) }}">Обновить</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Удалить</button>

      {% endif %}
</div>


      {% endif %}
    </div>
  </div>
</div>
  
<!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Удалить">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "layout.html" %}

{% block head %}
  <style>
    .container{
      margin-bottom: 0.8rem;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }
    
    .card-title{
      margin-bottom: 0 !important;
      font-family: 'Bebas Neue', cursive;
    }

    a{
      color: #003049 !important;
      text-decoration: none;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }

    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
  </style>
{% endblock head %}

{% block content %}
    <h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <div class="container" style="display: flex;">
      <article class="media" style="display: flex; flex-direction: column;"> 
        <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
      </article>
      
      <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
          <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

          <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
          <br>
          <br>
          <p class="card-text">{{ post.content }}</p>
        </div>
        <!-- <div class="card-footer" style="font-size: 20px;">
          <i class="fa fa-heart-o"></i>
          <i class="fa fa-bookmark-o"></i>
        </div> -->
      </div>
    </div>
    {% endfor %}

    
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}